### ISSUE TITLE
Implement Paketo RFC 0038: CycloneDX + Syft SBOM

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/nodejs#496]
To implement [Paketo RFC0038](https://github.com/paketo-buildpacks/rfcs/blob/932d89a970bea06c002496dbd6c7e3812ccab788/text/0038-cdx-syft-sbom.md), this buildpack (and the implementation buildpacks inside) will need to move from storing SBOM information in layer metadata to storing it in files that the CNB lifecycle can manipulate during the build. The RFC outlines what these files are and what they should contain. 

This issue serves as a meta-issue for work required to complete this work for the Nodejs language family. This will require (link Github issues as they are created):

- [ ] Updating SBOM format for node-engine buildpack https://github.com/paketo-buildpacks/node-engine/issues/408
- [ ] Updating SBOM format for yarn buildpack https://github.com/paketo-buildpacks/yarn/issues/177
- [ ] Generate `node_module` SBOM for npm apps https://github.com/paketo-buildpacks/npm-install/issues/296
- [ ] Remove the `node-module-bom` buildpack from the order groups in this language family
- [x] Generate `node_module` SBOM for yarn apps https://github.com/paketo-buildpacks/yarn-install/issues/280
- [x] ~Potentially, changes to yarn -start, npm-start, and node-start buildpacks to generate SBOMs as well~ Edit: Removing this step and deferring this work in these investigation issues:
    - paketo-buildpacks/yarn-start#170
    - paketo-buildpacks/npm-start#167

**Comment by fg-j** [comment]
This is currently blocked on adding sbom features in packit https://github.com/paketo-buildpacks/packit/pull/255

**Comment by robdimsdale** [comment]
If we remove the [node.js module bom buildpack](https://github.com/paketo-buildpacks/node-module-bom) then we should also remove it from the build plans defined in this meta buildpack. I'd feel comfortable using this issue to track that work, given it takes place in this repo.

**Comment by robdimsdale** [comment]
I can't edit the comment to add links directly, but I created some issues:

* [yarn-install](https://github.com/paketo-buildpacks/yarn-install/issues/280)
* [npm-install](https://github.com/paketo-buildpacks/npm-install/issues/296)

**Comment by sophiewigmore** [comment]
This is unblocked now that Packit v2.0.0 has been released

**Comment by fg-j** [comment]
Implementing this feature is blocked on platform integration issues.

**Comment by fg-j** [comment]
@paketo-buildpacks/nodejs-maintainers What's missing before we are able to close out this issue?

**Comment by ryanmoran** [comment]
I think this is done.
